### ISSUE TITLE
Clarify coordinates for chess2.2.genes for RefSeq entries

### ISSUE THREAD

**Issue by nh13** [chess-genome/chess#2]
I was looking at the `chess2.2.genes` file and this entry:
```
protein_coding  LMAN1   CHS.24766   chr18:59324939-59359276:-   RefSeq  3998    lectin%2C mannose binding 1
```

I figured that the coordinates would be the refseq coordinates from `chess2.2_and_refseq.gtf.gz`:
```
chr18  BestRefSeq  transcript  59327823  59359276  .  -  .  transcript_id  "CHS.24766.4";  gene_id  "CHS.24766";  gene_name  "LMAN1";
```

But instead it looks like the `chess2.2.genes` takes the smallest start coordinate and largest end coordinate from `chess2.2_and_refseq.gtf.gz`.  Is that correct?  If so, should the README have some more details?

**Comment by alevar** [comment]
Hi Nils,

Thank you for pointing this out! We will include a description of the columns for each file to clarify their meaning.

The .genes file describes coordinates as they are specified in the corresponding gene entries in the GFF3 annotation files. In the gff files, gene coordinates are indeed specified to be inclusive of all child transcripts/exons/CDS entries. The 5th column in the .genes file indicates the annotation where the gene has previously been annotated, but the coordinates might have been extended based on evidence from GTEx data.

Best,

Ales

**Comment by nh13** [comment]
> but the coordinates might have been extended based on evidence from GTEx data

This explains it, thank-you!  I'll leave this issue open for when the descriptions in the README are updated.
