### ISSUE TITLE
Update to use GRCh38.p13?

### ISSUE THREAD

**Issue by nh13** [chess-genome/chess#3]
The latest genome build is patch 13, versus patch 8 used here.  Any chance that either an updated version relative to the patch 13 can be made available, or describe if any annotations (if any) can be used between patches?

**Comment by alevar** [comment]
Hi Nils,

We are actively working on a new major release of the CHESS catalog, which is based on new alignments of the GTEx dataset against patch 12 of the GRCh38. We will have an extended description of the changes available once the release is finalized, but it will likely be similar to chess2.2_assembly in that it will exclude alternative scaffolds, patches and fixes of GRCh38. As such, both chess2.2_assembly and the upcoming release should be compatible with any patch of the GRCh38.

Are there any specific genes/features from CHESS v2.2 you are missing with patch 13 at the moment?

Best,

Ales

**Comment by nh13** [comment]
The number of missing features are very tiny, as they are only mapped to the new patches, so I am too concerned.  I would be very excited to use the new release and will watch this repository.  Thank-you for answering my questions.
