### ISSUE TITLE
Invalid feature coordinates

### ISSUE THREAD

**Issue by TheRealSmithLab** [chess-genome/chess#4]
Hi there! 

There seem to be some inconsistencies with several entries in the CHESS2.2 gffs. Running gffread on the files flagged several entries with incompatible exon coordinates. For example: 

> Error: invalid feature coordinates (end<start!) at line:
> chr1	FANTOM	exon	96813276	96813253	.	+	.	Parent=CHS.2297.45

The output of `grep CHS.2297.45 chess.gff` further highlights the problem: 

> chr1	FANTOM	transcript	96812803	96813405	.	+	.	ID=CHS.2297.45;Parent=CHS.2297;FANTOM_coding_status=noncoding;STATUS=known_fantom;ASSEMBLED=yes;FANTOM_functional_evidence=3;FANTOM_rnacode_call=yes;FANTOM_phylocsf_call=yes
> chr1	FANTOM	exon	96812803	96813106	.	+	.	Parent=CHS.2297.45
> chr1	FANTOM	exon	96813276	96813253	.	+	.	Parent=CHS.2297.45

**Comment by alevar** [comment]
Hi! Thank you for noticing the issue and bringing it to our attention! The versioning on the github repository was a little outdated and the more recent builds of the database have the issue corrected. We have now synced the latest release files between the webpage and the github repository.

Please let us know if you notice any other inconsistencies!

Best,

Ales

**Comment by xue-222** [comment]
> 

Did you solve the problem?

**Comment by alevar** [comment]
Hi! Yes, the problem has been resolved in more recent builds. Furthermore, we have now release a major revision to the Database (CHESS 3) based on complete re-evaluation of the GTEx data, using updated tools and a more informed filtering process (as well as many other improvements).

**Comment by TheRealSmithLab** [comment]
Thank you Ales! I will sleep (mildly) better tonight :-)
