### ISSUE TITLE
Will CHM13 CHESS3 annotations be available?

### ISSUE THREAD

**Issue by jelber2** [chess-genome/chess#6]
Hi,

I was wondering if the CHESS3 annotations will be available for the CHM13 T2T assembly as mentioned in the preprint?

**Comment by salzberg** [comment]
We have them and we meant to post them already - @alevar is working on this right now. We hope they will be visible from the CHESS website in the next few days, ccb.jhu.edu/chess.

**Comment by alevar** [comment]
Hi @jelber2,

Thank you for your interest in the CHESS annotation and my apologies for not having all the described files available at first. The missing annotations of the CHM13 (gff/gtf) have been committed to the repository and made available in the latest release). Changes are also reflected on the CHESS website.

Please let us know if you have any other question! if all looks good on your end - I will close this issue in 24 hours. Thank you and happy holidays

Ales

**Comment by jelber2** [comment]
Thank you very much!
