### ISSUE TITLE
CHESS3: Which method did you use to filter only coincident transcripts from the two obtained annotations? 

### ISSUE THREAD

**Issue by pclavell** [chess-genome/chess#7]
In your CHESS3 preprint methods section, in an effort to reduce transcriptional noise/artifacts you state "We only kept transcripts that were assembled in the initial samples, as well as after aggregating the alignments with TieBrush."
I'd like to ask which method did you use to merge only coincident transcripts, as I am only finding tools to merge full gtf files.

Thanks a lot

**Comment by alevar** [comment]
Hi,

To find transcripts models that were observed both in raw assemblies as well as after TieBrush filtering, we used gffcompare (https://github.com/gpertea/gffcompare). Gffcompare can be used to accomplish this task in several ways. For every query transcript, gffcompare will return a classification code (reported in the output GTF file as well as the tmap file). 

The full list of classification codes can be found in the gffcompare documentation at https://ccb.jhu.edu/software/stringtie/gffcompare.shtml. For example classification code "=" indicates that query transcript matches reference transcript. 

By comparing GTEx-assembled transcripts (query) to TieBrush-assembled transcripts (reference) and selecting only those that contain "=" code we selected only coincident transcripts. The only issue is that this technique does not work as well for single-exon transcripts, which we treated separately in our work.

Hope this information answers your question. Please let me know if I may be of assistance with anything else!

Thank you,

Ales

**Comment by pclavell** [comment]
Hi, yes, this is it. Thanks a lot!
