### ISSUE TITLE
Plans to include placenta samples?

### ISSUE THREAD

**Issue by vinjlynch** [chess-genome/chess#8]
Hi All, 

More a question than an issue. Unfortunately GTEx doesn't include placenta samples, are there plans to incorporate placental RNA-Seq data sets into CHESS?

Thanks,
Vinny

**Comment by alevar** [comment]
Hi Vinny,

Thank you for your interest in our catalogue! At the moment the CHESS catalogue is reliant entirely on the transcriptional evidence harnessed from the GTEx catalogue. Our current efforts are focused on increasing the confidence of our findings from that dataset as well as creating a more accessible presentation of the data for comparative analysis.

That being said, our updated protocol is versatile and robust to be applied to other datasets and is in fact currently being used by other groups to build focused catalogues based on other datasets. While we ourselves might not be looking to expand the main CHESS catalogue using placenta samples in the immediate future, if high-quality RNA-seq datasets exist, we would gladly assist anyone interested in applying our methods!

Sorry if this answer is not confirmatory, but I do hope in the future we can expand to additional resources and are happy to help anyone interested.

Thank you,

Ales
